apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: barista-s
  namespace: coffee-shop-serverless
  labels:
    app.kubernetes.io/part-of: coffee-shop
    app.openshift.io/runtime: quarkus
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 6s
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: coffee-shop
        app.openshift.io/runtime: quarkus
    spec:
      containerConcurrency: 0
      containers:
        - image: >-
            image-registry.openshift-image-registry.svc:5000/coffee-shop-serverless/barista:latest
          name: user-container
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
